[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"

[build]
rustflags = ["--cfg", "no_test"]

[profile.dev]
panic = "abort"
test = false

[profile.release]
panic = "abort"
test = false
